[server]
port = 5556

[node]
detect-drivers = false

[relay]
url = "http://localhost:4723"
status-endpoint = "/status"
configs = [
    "1", "{\"browserName\": \"chrome\", \"platformName\": \"Android\", \"appium:udid\": \"emulator-5554\", \"appium:platformVersion\": \"11\", \"appium:deviceName\": \"andr1\", \"appium:automationName\": \"uiautomator2\"}"
]