[server]
port = 5565

[node]
detect-drivers = false

[relay]
url = "http://localhost:4733"
status-endpoint = "/status"
configs = [
    "1", "{\"browserName\": \"chrome\", \"platformName\": \"Android\", \"udid\": \"emulator-5556\",\"platformVersion\": \"11\", \"appium:deviceName\": \"andr2\", \"appium:automationName\": \"uiautomator2\"}"
]