[server]
port = 5565

[node]
detect-drivers = false

[relay]
url = "http://localhost:4733"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:udid\": \"7taqv8o7bixoojby\",\"appium:platformVersion\": \"11\", \"appium:deviceName\": \"andr2\", \"appium:automationName\": \"uiautomator2\"}"
]